name: lsp-json-schema

channels:
  - conda-forge

dependencies:
  - black
  - click
  - git
  - hypothesis
  - hypothesis-jsonschema
  - isort
  - jupyterlab ==2.0.1
  - mypy
  - nodejs
  - pandas
  - pip
  - pyemojify
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-mypy
  - python >=3.8,<3.9.0a0
  - pyyaml
  - yarn
  - pip:
    - pytest-black
    - pytest-isort
